applications/contact/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from django.contrib.auth.decorators import login_required

from .views import ContactView

urlpatterns = [
    url(r'^$', (ContactView.as_view()), name='contact'),
]

unitedexports/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/en/', permanent=True)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^', include('applications.home.urls')),
    url(r'^contact-us/', include('applications.contact.urls')),
    url(r'^about-us/', include('applications.about.urls')),
    url(r'^products/', include('applications.product.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    prefix_default_language=True
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/contact/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from solo.models import SingletonModel


class Enquiry(models.Model):
    name = models.CharField(max_length=235)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Enquiry'
        verbose_name_plural = 'Enquiries'


class ContactEmail(SingletonModel):
    email = models.EmailField()

    def __str__(self):
        return self.email

applications/contact/forms.py
from django import forms

from .models import Enquiry


class EnquiryForm(forms.ModelForm):

    class Meta:
        model = Enquiry
        fields = ('name', 'email', 'message')

applications/contact/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
from django.views.generic import FormView, TemplateView
from django.conf import settings
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives
from django.http import HttpResponse
from django.http import JsonResponse

from .forms import EnquiryForm
from .models import ContactEmail


class ContactView(FormView):

    form_class = EnquiryForm
    template_name = "contact/contact.html"

    def form_valid(self, form):
        print(self.request.POST)
        text_template = get_template('email_templates/contact_message.html')
        user_name = form.cleaned_data['name']
        subject = 'Contact request by {}'.format(user_name)
        context = {'formentry': self.request.POST}
        text_content = text_template.render(context)
        from_email = settings.EMAIL_HOST_USER
        to = [ContactEmail.get_solo()]
        msg = EmailMultiAlternatives(subject, text_content, from_email, to)
        msg.attach_alternative(text_content, "text/html")
        msg.send()
        form.save()
        return JsonResponse({'status':'success'})

    def form_invalid(self, form):
        return HttpResponse(json.dumps({'result': {'status': 'form_error', 'errors': form.errors}}),
                            content_type='application/json')

templates/contact/contact.html
{% extends 'base.html' %}
{% load i18n %}
{% block extra_css %}
<style>
	.error{
		color: red;
		{% if not request.user_agent.is_mobile %}
		float: right !important;
		{% endif %}
	}
</style>
{% endblock %}
{% block content %}

<body class="res layout-1">
    
    <div id="wrapper" class="wrapper-fluid banners-effect-5">
    

    <!-- Header Container  -->
        {% include 'header.html' %}
    <!-- //Header Container  -->
    
	<!-- Main Container  -->
	<div class="main-container container">

		
		<div class="row">
			<div id="content" class="col-sm-12">
				<div class="page-title">
					<h2>Contact Us</h2>
				</div>
				
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2662.8346235923054!2d51.42960816414347!3d25.266415682148907!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e45d9875ab9b95f%3A0xff77f925646ba611!2sFamily+Shopping+Complex!5e0!3m2!1sen!2sin!4v1549772786706" width="100%" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
				<div class="info-contact clearfix">
					<div class="col-lg-4 col-sm-4 col-xs-12 info-store">
						<div class="row">
							<div class="name-store">
								<h3>Your Store</h3>
							</div>
							<address>
								<div class="address clearfix form-group">
									<div class="icon">
										<i class="fa fa-home"></i>
									</div>
									<div class="text">{% trans "The United Exporters" %}, {% trans "Furoosiya Street" %}, {% trans "Fareej al murra" %},
										{% trans "Doha" %}, {% trans "Qatar" %}</div>
								</div>
								<div class="phone form-group">
									<div class="icon">
										<i class="fa fa-phone"></i>
									</div>
									<div class="text">{% trans "Phone" %} : 44422798, 44422708, 77442798</div>
								</div>
								
							</address>
						</div>
					</div>
					<div class="col-lg-8 col-sm-8 col-xs-12 contact-form">
						<form id="contactform" method="post" class="form-horizontal">
							{% csrf_token %}
							<fieldset>
								<legend>{% trans "Contact Form" %}</legend>
								<div class="form-group required">
							<label class="col-sm-2 control-label" for="id_name">{% trans "Your Name" %}</label>
							<div class="col-sm-10">
								<input type="text" name="name" value="" id="id_name" class="form-control">
								</div>
							</div>
							<div class="form-group required">
								<label class="col-sm-2 control-label" for="id_email">{% trans "E-Mail Address" %}</label>
								<div class="col-sm-10">
									<input type="text" name="email" value="" id="id_email" class="form-control">
									</div>
								</div>
								<div class="form-group required">
									<label class="col-sm-2 control-label" for="id_message">{% trans "Enquiry" %}</label>
									<div class="col-sm-10">
										<textarea name="message" rows="10" id="id_message" class="form-control"></textarea>
									</div>
								</div>
							</fieldset>
							<div class="buttons">
								<div class="pull-right">
									<button class="btn btn-default buttonGray" id="btn-submit" type="submit">
										<span>{% trans "Send Enquiry" %}</span>
									</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- //Main Container -->



	<!-- Footer Container -->
    {% endblock %}
		{% block extra_js %}
				<script>
var count = 0;
$('#btn-submit').click(function() {
	<!--document.getElementById("success-message").innerHTML = "";-->
	var data = $('#contactform').serialize();
	var url = "{% url 'contact' %}"
	$('.error').html("");
    $('#successful').html("");
    document.getElementById("btn-submit").innerHTML = "Sending...";
	$.ajax({
		type: 'POST',
		url: url,
		data: data,
		cache : false,
		processData: false,

		success: function (response) {
			if (response.status == 'success') {
				$('.error').remove();
				document.getElementById("btn-submit").innerHTML = "{% trans 'SEND' %}";
				document.getElementById("success-message").innerHTML = "Message Sent Successfully";
				$('#contactform')[0].reset();
			}
			else if (response.result.status == 'form_error') {
				document.getElementById("btn-submit").innerHTML = "{% trans 'Send Enquiry' %}";
				if (count >= 1) {
					$('.error').remove();
				}
				$("#contactform :input:not(input[type='hidden'],input[type='submit'])").each(function () {
					var current = $(this).parent();
					var current_name = $(this).attr('name');
					$.each(response.result.errors, function (index, value) {
						if (current_name == index) {
							current.after("<div class='col-sm-10 error'></div></div>");
							current.next().html(value);
							count++;
						}
					});
				});
			}
		},
		error: function(error){}
	});
	return false;
});
</script>
		{% endblock %}